name: Cache Example CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: prime-cache-e4242db
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: cache-e4242db

      - name: Echo cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi

      - name: Install dependencies
        run: npm install
